// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_6zkHXcZXrtTFh4xI6hSiRp6UyW5hZ-w',
    appId: '1:118575930407:web:c54ae1ecc14c827bc6c202',
    messagingSenderId: '118575930407',
    projectId: 'e-commerce-d5b89',
    authDomain: 'e-commerce-d5b89.firebaseapp.com',
    storageBucket: 'e-commerce-d5b89.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5OFkR9maxuHCo51PMZfuMDVu8UlqBzeE',
    appId: '1:118575930407:android:72ca8ae17f5252b8c6c202',
    messagingSenderId: '118575930407',
    projectId: 'e-commerce-d5b89',
    storageBucket: 'e-commerce-d5b89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKMn_SgMBBQ590EF-ivT1cMg7vBO3K6Ms',
    appId: '1:118575930407:ios:252b8e9299379b6fc6c202',
    messagingSenderId: '118575930407',
    projectId: 'e-commerce-d5b89',
    storageBucket: 'e-commerce-d5b89.firebasestorage.app',
    iosBundleId: 'com.example.nexaraCart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKMn_SgMBBQ590EF-ivT1cMg7vBO3K6Ms',
    appId: '1:118575930407:ios:252b8e9299379b6fc6c202',
    messagingSenderId: '118575930407',
    projectId: 'e-commerce-d5b89',
    storageBucket: 'e-commerce-d5b89.firebasestorage.app',
    iosBundleId: 'com.example.nexaraCart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA_6zkHXcZXrtTFh4xI6hSiRp6UyW5hZ-w',
    appId: '1:118575930407:web:1a647e965cc29dc2c6c202',
    messagingSenderId: '118575930407',
    projectId: 'e-commerce-d5b89',
    authDomain: 'e-commerce-d5b89.firebaseapp.com',
    storageBucket: 'e-commerce-d5b89.firebasestorage.app',
  );
}
